# Generated by Django 2.0.2 on 2018-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=8)),
                ('name_title', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student_image/')),
            ],
            options={
                'ordering': ['faculty', 'major', 'student_id'],
            },
        ),
    ]
