# Generated by Django 2.0.2 on 2018-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(null=True, upload_to='student_image/'),
        ),
    ]
