# Generated by Django 2.0.2 on 2018-02-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180216_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_check', models.BooleanField(default=False)),
                ('second_check', models.BooleanField(default=False)),
                ('third_check', models.BooleanField(default=False)),
                ('first_stamp', models.DateTimeField()),
                ('second_stamp', models.DateTimeField()),
                ('third_stamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['student_id']},
        ),
        migrations.AddField(
            model_name='information',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='information',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Information'),
        ),
    ]
