# Generated by Django 2.0.2 on 2018-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180221_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='second_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='third_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
