# Generated by Django 2.0.2 on 2018-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180221_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='attendance',
        ),
        migrations.AddField(
            model_name='information',
            name='first_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='information',
            name='first_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='second_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='information',
            name='second_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='third_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='information',
            name='third_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
