# Generated by Django 2.0.2 on 2018-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180221_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='first_check',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='second_check',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='third_check',
            field=models.NullBooleanField(default=False),
        ),
    ]
