# Generated by Django 2.0.3 on 2018-03-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180301_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='first_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='second_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='third_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='information',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Degree'),
        ),
    ]
