# Generated by Django 2.0.3 on 2018-03-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180322_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Faculty'),
        ),
    ]
