# Generated by Django 2.0.3 on 2018-04-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_information_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_first', models.PositiveIntegerField(default=0)),
                ('order_last', models.PositiveIntegerField(default=0)),
                ('day', models.CharField(blank=True, max_length=256, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('load_place', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
